### ISSUE TITLE
Gestione Profilazione

### ISSUE THREAD

**Issue by DrBlink7** [doppiab-dev/RPG-Pal#8]
implementare API GET (N.B. header con bearer token) 
Descrizione: Informazioni sull’utente per una migliore UI/UX

```
/user/info
Response
interface UserInfo {
  username string | null
  player: { characters: number }
  master: { campaigns: number }
}
```

implementare API GET (N.B. header con bearer token) 
Descrizione: controllo di validazione della form di inserimento username per evitare errori sulla successiva chiamata API

```
/user/check/:username
Response
type UsernameCheck = boolean
```

implementare API POST (N.B. header con bearer token)
Descrizione: Aggiornamento username

```
/user/username
Req Body
interface Username {
  username: string
}
Response
204 (empty response)
```

**Comment by Zxcid** [comment]
API /user/info implementata
API /user/check/:username implementata
API /user/username implementata

TODO: test, swagger
